# -*- coding: utf-8 -*-
"""Naive bayes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12omF7WkftNVJmCRJXAszr7TYMNsFTrLX
"""

import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix

Data=pd.read_csv('/content/sample_data/IRIS.csv')

X=Data.drop('species',axis=1)
y=Data['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model=GaussianNB()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print("classification report:")
print(classification_report(y_test,y_pred))